# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VvyABUEXLuU7DrWGesXSUo0YhQA2_rgb
"""

def fibo(n):
  if n==0:
    return 0
  if n==1:
    return 1
  return fibo(n-1)+fibo(n-2)
print(fibo(int(input("ingrese el termino de la serie de fibonacci que desea conocer"))))