# -*- coding: utf-8 -*-
"""moduloHex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VvyABUEXLuU7DrWGesXSUo0YhQA2_rgb
"""

def suma(a,b):
  print(a+b)
def resta(a,b):
  print(a-b)
def multiplicion(a,b):
  print(a*b)
def divicion(a,b):
  print(a/b)
def potencia(a,b):
    c=1
    for i in range(b):
        c=c*a
    print(c)