# -*- coding: utf-8 -*-
"""moduloHex.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VvyABUEXLuU7DrWGesXSUo0YhQA2_rgb
"""

def sumahex(a,b):
  print(hex(int(a,16)+int(b,16)))
def restahex(a,b):
  print(hex(int(a,16)-int(b,16)))
def multhex(a,b):
  print(hex(int(a,16)*int(b,16)))
def divehex(a,b):
  print(float.hex(int(a,16)/int(b,16)))